name: Wolfboot Reusable Build Workflow for MCUXpresso SDK

on:

  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config-file:
        required: true
        type: string
      make-args:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/checkout@main
        with:
          repository: nxp-mcuxpresso/mcux-sdk
          path: mcux-sdk

      - uses: actions/checkout@main
        with:
          repository: nxp-mcuxpresso/CMSIS_5
          path: CMSIS_5

      - name: Workaround for sources.list
        run: sudo sed -i 's|http://azure.archive.ubuntu.com/ubuntu/|http://mirror.arizona.edu/ubuntu/|g' /etc/apt/sources.list

      - name: Update repository
        run: sudo apt-get update

      - name: Install cross compilers
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: make distclean
        run: |
          make distclean

      - name: Select config
        run: |
          cp ${{inputs.config-file}} .config && make include/target.h

      - name: Build tools
        run: |
          make -C tools/keytools && make -C tools/bin-assemble

      - name: Build wolfboot
        run: |
          make MCUXSDK=1 MCUXPRESSO="$GITHUB_WORKSPACE/mcux-sdk" MCUXPRESSO_CMSIS="$GITHUB_WORKSPACE/CMSIS_5/CMSIS" ${{inputs.make-args}} V=1
