name: Renode Automated multi memory configurations

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  renode_automated_fastmath_smallstack:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Select config
        run: |
          cp config/examples/nrf52840.config .config && make include/target.h


##### SMALL STACK + FAST MATH tests

# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 WOLFBOOT_SMALL_STACK=1 SPMATH=0"

# ECC521 TEST
      - name: Renode Tests ECC521
        run: ./tools/renode/docker-test.sh "SIGN=ECC521 WOLFBOOT_SMALL_STACK=1 SPMATH=0"

# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v4
        with:
          name: Renode Test Results
          path: test_results/

