name: trustzone-emulator-tests

on:
  push:
  pull_request:

jobs:
  trustzone-emulator-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/danielinux/m33mu-ci:1.3
    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git submodule update --init --single-branch

      - name: Configure stm32h5 (TZ) and build wolfboot
        run: |
          cp config/examples/stm32h5-tz.config .config
          make wolfboot.bin

      - name: Run emu test (stm32h5)
        working-directory: test-app/emu-test-apps
        run: |
          ./test.sh

      - name: Clean and build stm32u5 (TZ + wolfcrypt)
        run: |
          make clean distclean
          cp config/examples/stm32u5-wolfcrypt-tz.config .config
          make wolfboot.bin

      - name: Run emu test (stm32u5)
        working-directory: test-app/emu-test-apps
        run: |
          TARGET=stm32u5 ./test.sh

      - name: Clean and build stm32l5 (TZ + wolfcrypt)
        run: |
          make clean distclean
          cp config/examples/stm32l5-wolfcrypt-tz.config .config
          make wolfboot.bin

      - name: Run emu test (stm32u5)
        working-directory: test-app/emu-test-apps
        run: |
          TARGET=stm32l5 ./test.sh

      - name: Clean and build test with DICE attestation (stm32h5)
        run: |
          make clean distclean
          cp config/examples/stm32h5-tz-psa.config .config
          make
          m33mu wolfboot.bin test-app/image_v1_signed.bin:0x60000 --uart-stdout --expect-bkpt 0x7f --timeout 300

      - name: Clean and build test with DICE attestation + OTP (stm32h5)
        run: |
          make clean distclean
          cp config/examples/stm32h5-tz-psa-otp.config .config
          make
          make -C tools/keytools/otp TARGET=stm32h5 otp-keystore-primer.bin otp-keystore-gen
          ./tools/keytools/otp/otp-keystore-gen
          m33mu tools/keytools/otp/otp-keystore-primer.bin --persist --timeout 10 || true
          m33mu wolfboot.bin test-app/image_v1_signed.bin:0x60000 --uart-stdout --expect-bkpt 0x7f --timeout 300 --persist
