name: trustzone-emulator-tests

on:
  push:
  pull_request:

jobs:
  trustzone-emulator-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/danielinux/m33mu-ci:testing
    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git submodule update --init --single-branch

      - name: Configure stm32h5 (TZ) and build wolfboot
        run: |
          cp config/examples/stm32h5-tz.config .config
          make wolfboot.bin

      - name: Run emu test (stm32h5)
        working-directory: test-app/emu-test-apps
        run: |
          SCENARIOS=C ./test.sh

      - name: Clean and build stm32u5 (TZ + wolfcrypt)
        run: |
          make clean distclean
          cp config/examples/stm32u5-wolfcrypt-tz.config .config
          make wolfboot.bin

      - name: Run emu test (stm32u5)
        working-directory: test-app/emu-test-apps
        run: |
          TARGET=stm32u5 ./test.sh
